
const OFFICIAL_URL = "https://trouveo-market.netlify.app";
const BASE_ITEMS = [{"type": "product", "title": "Support téléphone voiture", "category": "Auto / Tech", "price": "À comparer", "city": "France", "desc": "Produit utile pour garder le téléphone stable et utiliser le GPS proprement.", "cta": "Comparer les offres", "url": "https://www.google.com/search?q=support+t%C3%A9l%C3%A9phone+voiture+meilleur+prix", "keywords": "telephone voiture support gps auto tech"}, {"type": "product", "title": "Organisateur de câbles bureau", "category": "Bureau / Maison", "price": "À comparer", "city": "France", "desc": "Produit simple pour ranger les câbles et garder un bureau propre.", "cta": "Comparer les offres", "url": "https://www.google.com/search?q=organisateur+c%C3%A2bles+bureau+meilleur+prix", "keywords": "bureau cables rangement maison"}, {"type": "product", "title": "Boîtes de rangement pliables", "category": "Maison / Rangement", "price": "À comparer", "city": "France", "desc": "Ranger vêtements, papiers, jouets ou objets du quotidien sans acheter un meuble.", "cta": "Comparer les offres", "url": "https://www.google.com/search?q=boites+rangement+pliables+meilleur+prix", "keywords": "maison rangement boite pliable"}, {"type": "deal", "title": "Mise en avant commerçant local", "category": "Publicité partenaire", "price": "Formule personnalisée", "city": "Local / France", "desc": "Emplacement prévu pour un commerçant, artisan ou service qui souhaite publier une promo ou une offre.", "cta": "Demander une mise en avant", "url": "#merchant", "keywords": "commerce local publicité partenaire promo"}, {"type": "deal", "title": "Bon plan restaurant / commerce", "category": "Bon plan local", "price": "Offre à renseigner", "city": "Ville à définir", "desc": "Espace prévu pour afficher une offre locale validée : restaurant, coiffeur, activité, boutique ou service.", "cta": "Proposer une offre", "url": "#merchant", "keywords": "restaurant commerce local promo offre"}, {"type": "service", "title": "Service local à promouvoir", "category": "Service", "price": "Sur devis", "city": "Ville à définir", "desc": "Fiche prête pour services locaux : réparation, nettoyage, artisan, livraison ou aide administrative.", "cta": "Contacter", "url": "#merchant", "keywords": "service artisan local devis"}];
const BASE_SUBS = [{"name": "Découverte", "price": "0 €", "desc": "Fiche simple en attente de validation, sans mise en avant."}, {"name": "Visible", "price": "10 €/mois", "desc": "Présence dans l’onglet Bons plans avec lien, ville et catégorie."}, {"name": "Boost", "price": "25 €/mois", "desc": "Mise en avant prioritaire + QR code offre + texte publicitaire."}, {"name": "Sur mesure", "price": "Personnalisé", "desc": "Formule négociée pour marché, association, commerce ou campagne locale."}];
const AD_TEXTS = {"client": "🔥 Trouvéo Market est lancé !\n\nUne seule plateforme pour découvrir :\n🛍️ des produits utiles\n📍 des bons plans autour de vous\n🏪 des commerçants locaux\n🎯 des offres partenaires\n📲 un accès rapide par QR code\n\nDécouvrez Trouvéo Market ici :\nhttps://trouveo-market.netlify.app", "merchant": "Vous êtes commerçant, artisan ou prestataire ?\n\nTrouvéo Market vous permet de proposer une offre, une promotion ou une mise en avant locale.\n\nObjectif :\n✅ gagner en visibilité\n✅ publier un bon plan\n✅ recevoir des demandes\n✅ apparaître dans une plateforme simple à partager par QR code\n\nDemandez votre mise en avant ici :\nhttps://trouveo-market.netlify.app", "tiktok": "Nouvelle idée locale 🚀\n\nUne seule plateforme pour chercher des produits utiles, découvrir des bons plans et mettre en avant les commerçants autour de vous.\n\nÇa s’appelle Trouvéo Market.\n\nBoutique + bons plans + commerçants + QR code.\nLien : https://trouveo-market.netlify.app\n\n#trouveo #bonsplans #commerceLocal #boutiqueenligne #startupfrance", "whatsapp": "Salut 👋\n\nJe te partage Trouvéo Market : une plateforme qui regroupe boutique, bons plans, offres locales et commerçants.\n\nLien : https://trouveo-market.netlify.app"};
let items = JSON.parse(localStorage.getItem("trouveo_market_items_v3") || "null") || BASE_ITEMS;
let subs = JSON.parse(localStorage.getItem("trouveo_market_subs_v3") || "null") || BASE_SUBS;
let lastPosition = null;
function normalizeText(s){return (s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function show(id){["market","shop","deals","nearby","merchant","subscriptions","publicity","owner"].forEach(x=>{const el=document.getElementById(x); if(el)el.classList.toggle("hidden",x!==id)}); render();}
function filtered(type){const q=normalizeText(document.getElementById("q").value); const tf=document.getElementById("typeFilter").value; return items.filter(i=>(!type||i.type===type)&&(!tf||i.type===tf)&&(!q||normalizeText(i.title+" "+i.category+" "+i.city+" "+i.desc+" "+(i.keywords||"")).includes(q)));}
function mapsUrl(q, city){if(lastPosition)return `https://www.google.com/maps/search/${encodeURIComponent(q)}/@${lastPosition.lat},${lastPosition.lng},14z`; return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent((q||"commerce")+" "+(city||""));}
function actionUrl(i){
  const raw = String(i.url || "").trim();
  if(!raw) return mapsUrl(i.title, i.city);
  if(raw.startsWith("#merchant")) return OFFICIAL_URL + "/#merchant";
  if(/^https?:\/\//i.test(raw) || /^mailto:/i.test(raw) || /^tel:/i.test(raw)) return raw;
  if(/^[+0-9 .()\-]{6,}$/.test(raw)) return "tel:" + raw.replace(/[^+0-9]/g, "");
  if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(raw)) return "mailto:" + raw;
  return "https://www.google.com/search?q=" + encodeURIComponent(raw);
}
function card(i,idx){const label=i.type==="product"?"Boutique":i.type==="deal"?"Bon plan":"Service"; return `<article class="card"><div class="tag">${label} · ${i.category}</div><h3>${i.title}</h3><div class="price">${i.price}</div><p>${i.desc}</p><p><b>Zone :</b> ${i.city}</p><div class="actions"><a class="btn" target="_blank" href="${actionUrl(i)}">${i.cta||"Voir"}</a><a class="btn alt" target="_blank" href="${mapsUrl(i.title,i.city)}">Autour</a><button class="darkbtn ownerOnly" onclick="archiveItem(${idx})">Archiver</button></div></article>`;}
function render(){document.getElementById("shop").innerHTML=filtered("product").map((i,idx)=>card(i,idx)).join("")||"<p class='sub'>Aucun produit.</p>"; document.getElementById("deals").innerHTML=filtered("deal").map((i,idx)=>card(i,idx)).join("")||"<p class='sub'>Aucun bon plan.</p>"; document.getElementById("subsGrid").innerHTML=subs.map(s=>`<article class="card"><div class="tag">Formule</div><h3>${s.name}</h3><div class="price">${s.price}</div><p>${s.desc}</p><div class="actions"><button class="btn" onclick="selectPlan('${String(s.name).replace(/'/g,"\\'")}')">Choisir</button></div></article>`).join(""); renderNearbyCards(); renderAds();}
function selectPlan(name){show("merchant"); const sel=document.getElementById("mSub"); if(sel)sel.value=name;}
function submitMerchantLocal(){const title=document.getElementById("mName").value.trim(); if(!title)return alert("Nom du commerce obligatoire."); items.unshift({type:"deal",title,category:document.getElementById("mCategory").value,price:document.getElementById("mOffer").value||"Offre à valider",city:document.getElementById("mCity").value||"Local",desc:(document.getElementById("mDesc").value||"Demande commerçant à valider.")+" · Formule demandée : "+document.getElementById("mSub").value,cta:"Voir / contacter",url:document.getElementById("mLink").value||OFFICIAL_URL,keywords:"demande commerçant publicité partenaire"}); save(); alert("Demande ajoutée localement."); show("deals");}
function unlock(){if(document.getElementById("pin").value==="1234"){document.getElementById("app").classList.add("ownerOn"); document.getElementById("locked").style.display="none"; alert("Espace propriétaire déverrouillé."); render();}else alert("Code incorrect.");}
function addOwnerItem(){const title=document.getElementById("oTitle").value.trim(); if(!title)return alert("Titre obligatoire."); items.unshift({type:document.getElementById("oType").value,title,category:document.getElementById("oCategory").value||"À classer",price:document.getElementById("oPrice").value||"À définir",city:document.getElementById("oCity").value||"France",desc:document.getElementById("oDesc").value||"",cta:"Voir",url:document.getElementById("oUrl").value||mapsUrl(title,document.getElementById("oCity").value),keywords:title}); save(); ["oTitle","oPrice","oCategory","oCity","oUrl","oDesc"].forEach(id=>document.getElementById(id).value=""); render(); alert("Ajouté.");}
function addSubscription(){const name=document.getElementById("sName").value.trim(); if(!name)return alert("Nom de formule obligatoire."); subs.push({name,price:document.getElementById("sPrice").value||"Sur mesure",desc:document.getElementById("sDesc").value||"Formule personnalisée."}); save(); ["sName","sPrice","sDesc"].forEach(id=>document.getElementById(id).value=""); render();}
function archiveItem(idx){if(!confirm("Archiver cet élément localement ?"))return; items.splice(idx,1); save(); render();}
function exportItems(){const blob=new Blob([JSON.stringify({items,subs},null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="trouveo_market_donnees.json"; a.click(); URL.revokeObjectURL(a.href);}
function save(){localStorage.setItem("trouveo_market_items_v3",JSON.stringify(items)); localStorage.setItem("trouveo_market_subs_v3",JSON.stringify(subs));}
function showQR(){document.getElementById("qrBox").classList.remove("hidden"); document.getElementById("qrImg").src="assets/qr-trouveo-market.png";}
function downloadQR(){const a=document.createElement("a"); a.href="assets/qr-trouveo-market.png"; a.download="QR_Trouveo_Market.png"; a.click();}
function copyLink(){navigator.clipboard.writeText(OFFICIAL_URL); alert("Lien officiel copié.");}
function openNearby(){const q=document.getElementById("nearbyQuery").value||document.getElementById("q").value||"bons plans"; const city=document.getElementById("nearbyCity").value||""; window.open(mapsUrl(q,city),"_blank");}
function renderNearbyCards(){const presets=["restaurant","téléphone","supermarché","coiffeur","garage","bricolage","électroménager","pharmacie"]; const city=document.getElementById("nearbyCity")?.value||""; document.getElementById("nearbyCards").innerHTML=presets.map(p=>`<article class="card"><div class="tag">Autour</div><h3>${p}</h3><p>Recherche rapide autour de toi ou de la ville indiquée.</p><div class="actions"><a class="btn alt" target="_blank" href="${mapsUrl(p,city)}">Ouvrir Maps</a></div></article>`).join("");}
function useGeo(){const box=document.getElementById("locationStatus"); box.classList.remove("hidden"); if(!navigator.geolocation){box.textContent="Géolocalisation non disponible sur ce navigateur."; return;} box.textContent="Demande de localisation en cours…"; navigator.geolocation.getCurrentPosition(pos=>{lastPosition={lat:pos.coords.latitude,lng:pos.coords.longitude}; box.textContent="Position détectée. Les boutons Autour utilisent maintenant ta position."; show("nearby"); render();},()=>{box.textContent="Localisation refusée ou bloquée. Tu peux utiliser une ville manuellement.";});}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR)return alert("Le micro vocal n’est pas compatible avec ce navigateur. Essaie Chrome."); const rec=new SR(); rec.lang="fr-FR"; rec.interimResults=false; rec.onresult=e=>{document.getElementById("q").value=e.results[0][0].transcript; render();}; rec.onerror=()=>alert("Micro bloqué ou refusé. Autorise le micro dans le navigateur."); rec.start();}
function labelAd(k){return {client:"Texte client",merchant:"Texte commerçant",tiktok:"Script TikTok",whatsapp:"Message WhatsApp"}[k]||k;}
function renderAds(){const box=document.getElementById("adTexts"); if(!box)return; box.innerHTML=Object.entries(AD_TEXTS).map(([key,text])=>`<article class="card"><div class="tag">Publicité</div><h3>${labelAd(key)}</h3><div class="copybox" id="ad_${key}">${text}</div><div class="actions"><button class="btn" onclick="copyAd('${key}')">Copier</button><button class="btn alt" onclick="shareAd('${key}')">Partager</button></div></article>`).join("");}
function copyAd(key){navigator.clipboard.writeText(AD_TEXTS[key]); alert("Texte copié.");}
function shareAd(key){const text=AD_TEXTS[key]; if(navigator.share)navigator.share({title:"Trouvéo Market",text,url:OFFICIAL_URL}); else window.open("https://wa.me/?text="+encodeURIComponent(text),"_blank");}
render();
